# Generated by cucumber-sinatra. (2013-09-23 14:56:16 +0100)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'app/bookmark_manager.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'
require 'database_cleaner'
require 'database_cleaner/cucumber'

DatabaseCleaner.strategy = :truncation

Capybara.app = BookmarkManager

class BookmarkManagerWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

Before do
  DatabaseCleaner.start
end

World do
  BookmarkManagerWorld.new
end

After do |scenario|
  DatabaseCleaner.clean
end